server:
  port: ${PORT}

elide:
  modelPackage: 'example.models'
  json-api:
    path: /json
    enabled: true
  graphql:
    path: /graphql
    enabled: true
  swagger:
    path: /doc
    enabled: true
    version: "1.0"


spring:
  jpa:
    hibernate:
      show_sql: true
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      dialect: 'org.hibernate.dialect.H2Dialect'
      ddl-auto: 'validate'
      jdbc:
        use_scrollable_resultset: true
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: 'org.hibernate.dialect.PostgreSQLDialect'
  liquibase:
    change-log: 'classpath:db/changelog/changelog.xml'
